closing the clients poc
iv-org/invidious pull request #1600
Opened 2020-12-23 05:54 UTC by azhao-squareup

this is a proof of concept, not code to merge

2020-12-24 19:17 UTC, azhao-squareup commented
this is finished now

2020-12-27 04:46 UTC, saltycrys requested changes

2020-12-27 04:46 UTC, saltycrys commented on src/invidious/helpers/utils.cr
> +def make_client(url : URI, region = nil)
```suggestion
def make_client(url : URI, region = nil, &block)
```
I think it's a good idea to be explicit here.

2020-12-27 04:51 UTC, saltycrys commented
This is off-topic but sometimes [lsquic](https://github.com/iv-org/lsquic.cr) `get` requests don't finish, any idea why that might happen?

2020-12-27 09:46 UTC, FireMasterK commented
Why not just use 1 client for all requests? It doesn't make sense to create a client for every request/host...

2020-12-28 00:46 UTC, unixfox commented
I'm really interested into this PR, maybe this could help https://github.com/iv-org/invidious/issues/1132

2020-12-28 00:52 UTC, jksladjflkjsadflkjsadf commented
> This is off-topic but sometimes [lsquic](https://github.com/iv-org/lsquic.cr) `get` requests don't finish, any idea why that might happen?

I noticed that happening too, but I don't really have expeirence with crystal bindings or quic, so I have no idea right now.  I might take a look later.



> I'm really interested into this PR, maybe this could help solving #1132

Unfortunately this won't help with that, because the error is coming from the quic pool clients.


> Why not just use 1 client for all requests? It doesn't make sense to create a client for every request/host...

1 client is not enough, but this idea is what we are doing with the pooled request clients in YT_POOL.  But for the client to be reusable, it needs to be reused for the same host as the original, which is not applicable for the youtube cdn and some other uses.

2020-12-28 19:41 UTC, saltycrys approved these changes

2020-12-28 19:46 UTC, saltycrys commented on src/invidious/helpers/utils.cr
> +def make_client(url : URI, region = nil)
This is resolved but I can't mark it as resolved because of the force-pushes.

2020-12-29 20:52 UTC, jksladjflkjsadflkjsadf commented
@TheFrenchGhosty are you able to merge this?

2020-12-30 01:14 UTC, merged

2020-12-30 01:14 UTC, TheFrenchGhosty commented
Thanks!