Enhance search filter UI for JS disabled users
iv-org/invidious pull request #1837
Opened 2021-03-01 11:56 UTC by syeopite

Allow JS disabled users to collapse the search filter list.

2021-03-03 23:00 UTC, saltycrys requested changes

2021-03-03 23:00 UTC, saltycrys commented on assets/css/default.css
> +}
Please remove the duplicated styles and add a space.

2021-03-03 23:00 UTC, saltycrys commented on src/invidious/views/search.ecr
> +</details>
Please indent the `div`.

2021-03-13 13:01 UTC, saltycrys requested changes
The indentation of the file is four spaces, so any changes should also be indented by four spaces.

2021-03-17 16:54 UTC, TheFrenchGhosty commented
@saltycrys Can you please review this PR?

2021-03-19 17:27 UTC, saltycrys requested changes

2021-03-19 17:27 UTC, saltycrys commented on src/invidious/views/search.ecr
> +<script src="/js/search.js?v=<%= ASSET_COMMIT %>"></script>
Please remove this.

2021-03-19 20:24 UTC, saltycrys approved these changes

2021-03-19 20:32 UTC, merged

2021-03-19 20:32 UTC, TheFrenchGhosty commented
Thank you! @syeopite 

Thanks for the review @saltycrys