Add instance redirects!
iv-org/invidious pull request #1940
Opened 2021-03-27 05:16 UTC by syeopite

Add functions that allow users to be redirected to a random clear-net invidious instance on videos and search.

There's also a few front end additions.

<img src="https://user-images.githubusercontent.com/70992037/112710170-0f319880-8eb7-11eb-92e0-706b7976066d.png" width="268" height="172">

The jet icon here is just a placeholder. I couldn't find any v4 ion icon that fits.
<img src="https://user-images.githubusercontent.com/70992037/112710342-376dc700-8eb8-11eb-84c6-c49856f9ac47.png">

There's also a search redirect for when searching is broken. The filtering UI has been hidden to provide prominence to that message.
 ![redirect-3](https://user-images.githubusercontent.com/70992037/112710250-88c98680-8eb7-11eb-9924-c2ba9b774bdf.png)

Anyhow, this feature works by fetching an instance list from [api.invidious.io](https://api.invidious.io) so the load on that server would increase if merged. 

PS: I have no idea what I'm doing when it comes to crystal.

2021-03-27 05:19 UTC, syeopite commented
Related #944

2021-03-28 20:25 UTC, TheFrenchGhosty commented
>Anyhow, this feature works by fetching an instance list from api.invidious.io so the load on that server would increase if merged.

This isn't really a problem, the server has enough bandwidth to handle the requests, so this is fine.

2021-03-29 03:48 UTC, saltycrys requested changes

2021-03-29 03:48 UTC, saltycrys commented on src/invidious/routes/misc.cr
> +  def redirect(env)
Please change this to be generic, something like https://github.com/iv-org/invidious/blob/c9a316ad353cd1ee38c34d1aff0759765b37b2b3/src/invidious/views/template.ecr#L63

2021-04-01 08:43 UTC, unixfox commented
Is this really a good idea? What if it redirects to an instance that is down? api.invidious.io doesn't do a health check so that can happen.

Wouldn't it be better to redirect to https://redirect.invidious.io instead? This way the user can choose whatever instance he wants instead of random one and has a clear list of all the existing public instances.

2021-04-01 10:14 UTC, TheFrenchGhosty commented
Mmh I kinda agree with @unixfox here.

It would also simplify the code a lot.

2021-04-02 04:35 UTC, syeopite commented
> Is this really a good idea? What if it redirects to an instance that is down? api.invidious.io doesn't do a health check so that can happen.

Good point though the chances of running into an dead instance are pretty slim. I instance hop frequently and I've only ever encountered an instance that is down once. It's far more likely to reach a outdated instance instead. The latter of which can be solved if we just compared the versions to the current one.

Personally I prefer this version more than the only redirect to [https://redirect.invidious.io](https://redirect.invidious.io). Its less work on the users end and even allows for site routes to pass through for JS disabled users.

2021-04-06 13:28 UTC, saltycrys approved these changes

2021-04-08 08:45 UTC, Perflyst commented
How do we continue with this one? I also prefer redirect.invidious.io...

> Personally I prefer this version more than the only redirect to https://redirect.invidious.io. Its less work on the users end and even allows for site routes to pass through for JS disabled users.

redirect.invidious.io works without javascript too (not completely though)

2021-04-11 12:37 UTC, syeopite commented
Compromise and allow it to be configurable?

2021-05-16 06:24 UTC, syeopite commented
There we go. All of these concerns has been addressed.

2021-06-14 09:03 UTC, unixfox commented
What happens if api.invidious.io is down? Does it skip the rendering of the link?

2021-06-14 10:10 UTC, syeopite commented
`redirect.invidious.io` would be used instead.

2021-06-14 10:16 UTC, syeopite commented
I'll like to add to my previous argument about potentially redirecting to instances that are down. `api.invidious.io` currently refreshes its instance list every 5 minutes; any instance that is down for longer than that would quickly be removed from the API as well.

2021-06-14 10:35 UTC, unixfox commented
> I'll like to add to my previous argument about potentially redirecting to instances that are down. `api.invidious.io` currently refreshes its instance list every 5 minutes; any instance that is down for longer than that would quickly be removed from the API as well.  

Not if the API starts to freeze, which often happens and need a restart.

2021-06-14 16:38 UTC, TheFrenchGhosty commented
@unixfox The api has a cronjob that restart it daily

2021-06-14 17:36 UTC, unixfox commented
> @unixfox The api has a cronjob that restart it daily

If the API happens to freeze before the restart for whatever reason, this system will still offer instances that could be down until the API is restarted.

Unless this system rely on a reliable healthcheck service like uptime robot, there will be cases where an instance that is down could be offered to the user.

2021-06-14 19:42 UTC, syeopite commented
Even if one got redirected to an instance that is down —  the chance of which is already extremely low — how is it any different from clicking on an instance that is down on redirect.invidious.io? In both cases you'll have to go back to the original page and pick a new instance or in the case of this PR click on the switch instance button again

2021-06-14 19:48 UTC, unixfox commented
> Even if one got redirected to an instance that is down — the chance of which is already extremely low — how is it any different from clicking on an instance that is down on redirect.invidious.io? In both cases you'll have to go back to the original page and pick a new instance or in the case of this PR click on the switch instance button again

On redirect.invidious.io, multiple instances get presented to you. With your system, only one is given.
If an instance is down from redirect.invidious.io then the user will probably understand a bit better that he can try another one because he saw multiple instances available.
Whereas with your system just one link is given and the user may not understand directly that it can come back to the previous page THEN refresh the page for getting another instance.

2021-06-16 07:24 UTC, syeopite commented
Good point, though you exactly don't need to refresh the page to head to another instance. Just going back to the previous page would be enough to get reconnected to another instance as any connection to the `/redirect` endpoint would cause a redirect.

2021-06-19 11:35 UTC, merged