Add the ability to listen on UNIX sockets
iv-org/invidious pull request #2111
Opened 2021-05-22 15:47 UTC by unixfox

Kemal allows native ability to listen on UNIX sockets: https://kemalcr.com/cookbook/unix_domain_socket/. This pull request add the ability to configure the UNIX sockets on Invidious.

On some environments, especially Docker, this can improve the requests throughput up to 40%: https://blog.myhro.info/2017/01/benchmarking-ip-and-unix-domain-sockets-for-real! A very small Invidious instance won't notice this gain of performance but on a high demand instance with a lot of requests this can improve the latency and the amount of requests that an instance can serve.

2021-05-22 15:59 UTC, SamantazFox commented
To avoid adding another config option, that would require more documentation and confuse people, wouldn't it be better to rename `host_binding` to something like `listen` (similar to many other programs) and allow both IPv4/IPv6 and unix socket to be specified here?

2021-05-22 16:03 UTC, FireMasterK commented
I feel like properly documenting this would be a better idea instead.

I feel this way because IP stacks have a port in addition, which Unix sockets do not have.

2021-05-22 16:19 UTC, SamantazFox commented
> I feel like properly documenting this would be a better idea instead.
> 
> I feel this way because IP stacks have a port in addition, which Unix sockets do not have.

Yeah, but having a lot of mutually exclusive options not going to make documentation easier (Trust me, I'm behind #2083). The postgreSQL config already has two forms, and that's not intuitive (most projects I know, if not all, only have one form or the orther, but not both). Having more cases like that is going to make things worse.

2021-05-22 16:20 UTC, unixfox commented
> To avoid adding another config option, that would require more documentation and confuse people, wouldn't it be better to rename `host_binding` to something like `listen` (similar to many other programs) and allow both IPv4/IPv6 and unix socket to be specified here?

I get what you are trying to say, allow the ability to set both an IP address with a port or a unix socket in a same YAML field called `listen`. Am I right? If so, the issue is that I don't really want to do the fun part of detecting if it's an IP address or path that is passed to the field.

UNIX sockets are already a niche use case and for most of the people their setup will still work as expected. If one wants to configure UNIX socket, I think he will be tech-savvy enough to understand the differences between `host_binding` and `bind_unix`. I do consider that the field `bind_unix` is maybe not a correct name and should be renamed to a more appealing field.

2021-05-22 17:19 UTC, SamantazFox commented
> I get what you are trying to say, allow the ability to set both an IP address with a port or a unix socket in a same YAML field called `listen`. Am I right? If so, the issue is that I don't really want to do the fun part of detecting if it's an IP address or path that is passed to the field.

Simply that?
```
if CONFIG.listen.startsWith('/')
  # UNIX socket
else
  # Network interface
end
```

2021-05-22 17:42 UTC, unixfox commented
> > I get what you are trying to say, allow the ability to set both an IP address with a port or a unix socket in a same YAML field called `listen`. Am I right? If so, the issue is that I don't really want to do the fun part of detecting if it's an IP address or path that is passed to the field.
> 
> Simply that?
> 
> ```
> if CONFIG.listen.startsWith('/')
>   # UNIX socket
> else
>   # Network interface
> end
> ```

Won't work if you are on Windows, paths on Windows start with a letter of the drive.

2021-05-22 17:58 UTC, SamantazFox commented
> Won't work if you are on Windows, paths on Windows start with a letter of the drive.

Do Windows support unix sockets? And also, is invidious able to run natively on Windows (without a Linux docker container)?

2021-05-22 18:20 UTC, unixfox commented
> > Won't work if you are on Windows, paths on Windows start with a letter of the drive.
> 
> Do Windows support unix sockets? And also, is invidious able to run natively on Windows (without a Linux docker container)?

It's possible, but it doesn't really work the same way: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/. Just forget what I said.

Anyway, I really don't want to do the fun part of parsing the IP address from the port if we remove the "port" field too. Example: `0.0.0.0:3000` or `[::]:3000`.
And also we will need to do a backward compatibility with the existing fields "host_binding" and "port".

2021-05-22 18:25 UTC, SamantazFox commented
> Anyway, I really don't want to do the fun part of parsing the IP address from the port if we remove the "port" field too. Example: `0.0.0.0:3000` or `[::]:3000`.

Imo we should still keep the current port config, to avoid code clutter.

2021-05-22 18:43 UTC, unixfox commented
> > Anyway, I really don't want to do the fun part of parsing the IP address from the port if we remove the "port" field too. Example: `0.0.0.0:3000` or `[::]:3000`.
> 
> Imo we should still keep the current port config, to avoid code clutter.

That will make things even more confusing then, having the ability to set an IP address but not the port on a field just called `listen`... I think if we don't move forward and still keep the `port` field then I would prefer to add the ability to set a unix socket on the `host_binding` field instead then. At least we don't have to do backward compatibility.

I'm still wondering if `bind_unix` is not the optimal solution because in this case we don't break any potential weird configuration and no need for parsing the field in order to detect a path or an IP address.

2021-05-22 19:17 UTC, FireMasterK commented
> Do Windows support unix sockets?

They surprisingly do! Although, the included curl version doesn't support them.

I may have a solution of solving this:
```
if(value.endsWith(".sock")) {
     // bind to a socket here
} else {
      String ip = value.substring(0, value.lastIndexOf(":"));
      String  port = value.substring(value.lastIndexOf(":") + 1);
     // bind to IP here
}
````

idk how this can be done in Crystal tho

2021-05-22 19:26 UTC, unixfox commented
> > Do Windows support unix sockets?
> 
> They surprisingly do! Although, the included curl version doesn't support them.
> 
> I may have a solution of solving this:
> 
> ```
> if(value.endsWith(".sock")) {
>      // bind to a socket here
> } else {
>       String ip = value.substring(0, value.lastIndexOf(":"));
>       String  port = value.substring(value.lastIndexOf(":") + 1);
>      // bind to IP here
> }
> ```
> 
> idk how this can be done in Crystal tho

But what if someone wants to name is file with something else than ending with `.sock`? That's not a proper solution.

2021-05-22 19:43 UTC, FireMasterK commented
> But what if someone wants to name his file with something else than ending with .sock? That's not a proper solution.

```
if(value.contains(File.separator) || !value.contains(":")) { // this is os independant because File.separator is `\` on windows and `/` on linux
    // bind to a socket here
}
```

This should do the trick.

2021-05-22 19:58 UTC, SamantazFox commented
> ```
> if(value.contains(File.separator) || !value.contains(":")) { // this is os independant because File.separator is `\` on windows and `/` on linux
>     // bind to a socket here
> }
> ```
> 
> This should do the trick.

`value.contains(":")` will match IPv6 addresses, so that won't work.

2021-05-22 20:03 UTC, FireMasterK commented
> value.contains(":") will match IPv6 addresses (and !value.contains(":") will match IPv4 addresses), so that won't work.

`!value.contains(":")` does not matches both `0.0.0.0:3000` and `[::]:3000` because they both contain `:`?

I'm not sure what you meant here 😄

2021-05-23 00:53 UTC, SamantazFox commented
> `!value.contains(":")` does not matches both `0.0.0.0:3000` and `[::]:3000` because they both contain `:`?
> 
> I'm not sure what you meant here 😄

Oh, my bad, I stayed on the idea of having only IP addresses, without a port :X

2021-06-19 18:24 UTC, syeopite requested changes
Looks good to me.  Just go ahead and merge bind_unix and host_binding like what everyone else wants here.

2021-06-19 18:26 UTC, SamantazFox commented
Same as @syeopite. What you can possibly do is check the input against the regexes below, in that order, and if none matches, then this is a unix socket.

Regex: `\[(?<ipv6>([0-9A-Fa-f]{0,4}:){2,}[0-9A-Fa-f]{0,4}\](?<port>:\d+)?`

=> matches IPV6 addresses, with or without a port number (`[::]`, `[::]:3000`, `[dead:beef::1]`, `[c0:ffee::42]:666`)

Regex: `(?<ipv4>(\d\.){3}\d)(?<port>:\d+)?`

=> matches IPV4 addresses, with or without a port number (`0.0.0.0`, `0.0.0.0:3000`, `127.0.0.1`, `10.42.0.2:666`)

2021-08-30 13:30 UTC, unixfox commented
bump

2021-11-18 09:47 UTC, closed without merging

2024-12-10 17:35 UTC, Caian commented
I'm willing to continue the development of this feature because I found podman networking struggles a lot in rootless mode, especially when streaming videos. Sockets are a nice solution to get better performance if Invidious is behind a proxy.

My idea for the configuration is to keep `host_binding` (let's not break existing configurations), instead use `port=0` to switch between `host_binding` and `socket_binding=<path-to-socket>`.

This idea comes from [the way Nextcloud is configured to talk with Redis](https://help.nextcloud.com/t/redis-unix-socket/129153).

As for the name `socket_binding`, I think it keeps consistency with `host_binding` and, when using docker, sockets are pretty much available on Windows as well, so it's not a Unix thing anymore.

What do you think?

2024-12-11 12:59 UTC, unixfox commented
Good idea for the naming `socket_binding`.

About `port=0`, you don't need to do such thing. You can just check if `socket_binding` is set, if it is then use it exclusively over `host_binding`.

2024-12-11 23:27 UTC, Caian commented
> Good idea for the naming `socket_binding`.
> 
> About `port=0`, you don't need to do such thing. You can just check if `socket_binding` is set, if it is then use it exclusively over `host_binding`.

I agree. I was trying to go for a configuration that's ambiguity-free and wouldn't allow 2 valid configurations set at the same time, but as you mentioned in a previous post: users of this feature are probably tech-savvy enough to understand.