Debloat channels.cr into mult files + rm depre.
iv-org/invidious pull request #2225
Opened 2021-06-28 23:35 UTC by syeopite

Cherry picked from #2215 with a few modifications:
  - channel folder is renamed to channels
  - parsing for channel home and featured channels are removed due to
    lack of infrastructure from other commits

(cherry picked from commit 44d18b8e147b47ad06a54cc6fd08423d9f39074d)

2021-06-29 10:03 UTC, SamantazFox commented
Can you please keep `produce_channel_playlists_url` around? The informations about the "playlists" protobuf object contained in this function is important!

2021-06-29 16:29 UTC, syeopite commented
Done

2021-07-10 16:46 UTC, SamantazFox requested changes

2021-07-10 16:48 UTC, SamantazFox commented on src/invidious.cr
> +require "./invidious/channels/**"
As in `spec/helpers_spec.cr`, this should be a single star, to match all files in the `channels` directory, unless you plan to plan to add subfolders, in this case this is the spec file that needs to be fixed.

2021-07-11 18:09 UTC, SamantazFox approved these changes

2021-07-12 14:05 UTC, SamantazFox commented
@syeopite I just realized that `country` and `links` elements in the `AboutChannel` struct aren't part of the original source code (probably some leftover of your other changes). Could you just remove those?

https://github.com/syeopite/invidious/blob/5bcb689804b214229967c955e9e132a66c131186/src/invidious/channels/about.cr#L2-L22

https://github.com/syeopite/invidious/blob/5bcb689804b214229967c955e9e132a66c131186/src/invidious/channels/about.cr#L141-L144

2021-07-13 01:01 UTC, syeopite commented
Oops, somehow missed that during cherry-picking. Should be fixed now.

2021-07-14 15:46 UTC, merged