Add compile-time flag to remove code for QUIC
iv-org/invidious pull request #2364
Opened 2021-08-30 21:56 UTC by syeopite

2021-08-31 21:52 UTC, syeopite commented
Using Invidious without QUIC has some  issues

2021-09-01 11:57 UTC, unixfox commented
Why this got closed? I know how to fix the issues.

2021-09-28 22:15 UTC, syeopite commented
There we go, that should fix the gzip issues. However, in order to make Invidious fully functional without lsquic, we're going to need to replace the few dozen usages of `:authority` with a HTTP/1.1 equivalent; otherwise, we can't support images. It's a bit out of scope for this PR though.

2021-09-28 23:05 UTC, SamantazFox requested changes

2021-09-28 23:05 UTC, SamantazFox commented on src/invidious/routes/login.cr
> +          client = QUIC::Client.new(LOGIN_URL)
```suggestion
          client = CONFIG.use_quic ? QUIC::Client.new(LOGIN_URL) : HTTP::Client.new(LOGIN_URL)
```

2021-09-28 23:05 UTC, SamantazFox commented on src/invidious/routes/login.cr
> +        client = nil # Declare variable
ditto not required

2021-09-28 23:05 UTC, SamantazFox commented on src/invidious/helpers/utils.cr
> +  alias ConnectonClientType = QUIC::Client | HTTP::Client
typo, should be `Connection`

2021-09-29 00:18 UTC, syeopite commented on src/invidious/helpers/utils.cr
> +      conn = nil # Declare
It is actually required. The `disable_quic` logic is considered a macro(?) so we can't actually access `conn` unless we declare it outside first. You can try to build Invidious without this yourself, but it'll just result in a compile time error.

2021-09-29 00:42 UTC, SamantazFox commented on src/invidious/helpers/utils.cr
> +      conn = nil # Declare
Whaaaa, even the inline version doesn't work!
`conn = {% unless flag?(:disable_quic) %} use_quic ? QUIC::Client.new(url) : {% end %} HTTP::Client.new(url)`

This is definitely an upstream bug...

2021-09-29 00:47 UTC, SamantazFox commented on src/invidious/helpers/utils.cr
> +      conn = nil # Declare
That works, though:

```crystal
conn = (
  {% unless flag?(:disable_quic) %}
    CONFIG.use_quic ? QUIC::Client.new(url) : HTTP::Client.new(url)
  {% else %}
    conn = HTTP::Client.new(url)
  {% end %}
)
```

2021-10-03 17:17 UTC, TheFrenchGhosty commented
Blocked by https://github.com/iv-org/invidious/pull/2364#issuecomment-929664683

2021-10-13 20:07 UTC, syeopite commented
Running this PR causes the following to be outputted within the logs occasionally. Though, it doesn't seem to actually cause any noticeable effect.


<details>

```
Exception: SSL_connect: I/O error (OpenSSL::SSL::Error)
  from /usr/share/crystal/src/openssl/ssl/socket.cr:34:11 in 'initialize'
  from /usr/share/crystal/src/openssl/ssl/socket.cr:3:5 in 'new:context:sync_close:hostname'
  from src/invidious/helpers/crystal_class_overrides.cr:34:5 in 'io'
  from /usr/share/crystal/src/http/client.cr:664:5 in 'send_request'
  from /usr/share/crystal/src/http/client.cr:599:5 in 'exec_internal_single'
  from /usr/share/crystal/src/http/client.cr:586:5 in 'exec_internal'
  from /usr/share/crystal/src/http/client.cr:581:7 in 'exec'
  from /usr/share/crystal/src/http/client.cr:706:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:738:7 in 'exec'
  from /usr/share/crystal/src/http/client.cr:406:3 in 'head'
  from src/invidious.cr:1514:7 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:68:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
Caused by: SSL_connect: Success (RuntimeError)
```

</details>

2021-11-02 02:11 UTC, syeopite commented on src/invidious/yt_backend/youtube_api.cr
> +    {% unless flag?(:disable_quic) %}
TODO: Check for the configuration option as well

2021-11-07 13:32 UTC, SamantazFox requested changes

2021-11-08 19:54 UTC, SamantazFox requested changes

2021-11-08 19:54 UTC, SamantazFox commented on src/invidious/routes/images.cr
> +          end
I'm wondering something: why isn't the `if CONFIG.use_quic` check made at the `YT_POOL` pool level, rather than here?

2021-11-12 12:05 UTC, syeopite commented
Just added a commit to disable quic by default due to #2577. Once merged, assuming the user hasn't modified the `use_quic` attribute, Invidious should work ootb.

2021-11-12 12:58 UTC, merged

2021-11-12 18:11 UTC, unixfox commented
For what is QUIC still used in the invidious code?

2021-11-12 22:38 UTC, syeopite commented
QUIC shouldn't be used at all now when either `use_quic` is turned off, or the compile time flag `disable_quic` is applied. 

To be absolutely certain of that, you can just go with the latter route and remove the dependency entirely from the libs folder.