Add CSV Subscriptions Import
iv-org/invidious pull request #2545
Opened 2021-10-27 23:21 UTC by bbielsa

Closes #2319 

1. Add a helper function `parse_subscription_export_csv()` to `helpers/utils.cr`, this function reads the body as CSV content, and parses the channel id column from the rows. 
2. Modify `invidious.cr` to perform a check on the body to determine if it is likely JSON (if so, the continue to use the current code for importing subscriptions). Otherwise, default to assuming it is in CSV format and parse the subscription export dump with the new helper function.

In the helper function, I used column index (in this case 0 corresponds to the `"Channel Id"` column), because I believe, based off of the bug report, that the header names are localized depending on the users language in this case "Kanal" = "Channel"

2021-10-29 21:51 UTC, bbielsa commented on src/invidious.cr
> +        elsif body[0] == '['
Would it be worth replacing these string comparison checks for determining content type and instead use the Content-Type header? https://crystal-lang.org/api/1.2.1/HTTP/FormData/Part.html#headers%3AHTTP%3A%3AHeaders-instance-method

2021-10-30 14:22 UTC, SamantazFox commented on src/invidious.cr
> +        elsif body[0] == '['
mmmh, you're right!

2021-11-03 04:45 UTC, bbielsa commented on src/invidious.cr
> +        elsif body[0] == '['
Fixed

2021-11-03 04:45 UTC, bbielsa commented on src/invidious/helpers/utils.cr
> +end
Fixed

2021-11-03 15:13 UTC, unixfox commented
In testing on https://yewtu.be

2021-11-04 20:20 UTC, SamantazFox requested changes

2021-11-04 20:20 UTC, SamantazFox commented on src/invidious/helpers/utils.cr
> +require "csv"
this should be in `imports.cr`, with the code requiring it

2021-11-04 20:20 UTC, SamantazFox commented on src/invidious/user/imports.cr
> +  subscriptions
please use a `return` statement here. While it's functionally the same thing, it makes the code more explicit :)

2021-11-06 21:58 UTC, unixfox commented
Probably a related issue: https://github.com/iv-org/invidious/issues/2566
Need to be investigated.

2021-11-07 17:34 UTC, bbielsa commented
I think it may be related to the logic for parsing the uploaded data. Currently the way it works is:

1. The POST handler checks the MIME type of the uploaded file
2. If the type matches `application/xml` or `text/xml`, then parse as XML
3. If the type matches `application/json`, then parse as JSON
4. Else, parse as CSV

I can explicitly check for the CSV MIME type, and I was going to do this originally, but it introduces the case where the user can upload any other type of file and there was no function to call that will return a simple user-readable error. What I can do is update the logic:

1. The POST handler checks the MIME type of the uploaded file
2. If the type matches `application/xml` or `text/xml`, then parse as XML
3. If the type matches `application/json`, then parse as JSON
4. If the type matches `text/csv`, then parse as CSV
5. Else, throw exception which shows the stack trace (may not be good for the user experience, but admittedly better than what I have created now)

A note for clarity: the "if type matches x" are the if statement cases in this commit https://github.com/iv-org/invidious/pull/2545/commits/0e138d64efe86cec4e9d70ddc0f49747fdc44a35

2021-11-08 13:00 UTC, unixfox commented
Why not having multiples fields for csv and json?
Like this:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/4016501/140746216-ed75f1e0-65a4-4d92-8a3e-c46de7bd3fc8.png">

2021-11-09 20:02 UTC, SamantazFox commented
> Why not having multiples fields for csv and json? Like this: <img alt="image" width="277" src="https://user-images.githubusercontent.com/4016501/140746216-ed75f1e0-65a4-4d92-8a3e-c46de7bd3fc8.png">

This is confusing. Some users already complained that there are too many import options.

@bbielsa Is it possible to check the filename? so `if type == 'foo' || name.ends_with?(".foo")`.

2021-11-14 23:37 UTC, SamantazFox commented
> Is it possible to check the filename? so `if type == 'foo' || name.ends_with?(".foo")`.

@bbielsa bump

2021-11-17 04:52 UTC, bbielsa commented
> > Why not having multiples fields for csv and json? Like this:
> > <img alt="image" width="277" src="https://user-images.githubusercontent.com/4016501/140746216-ed75f1e0-65a4-4d92-8a3e-c46de7bd3fc8.png">
> 
> This is confusing. Some users already complained that there are too many import options.
> 
> @bbielsa Is it possible to check the filename? so `if type == 'foo' || name.ends_with?(".foo")`.

I can check the file name, but in the event that the file is not XML, JSON, nor CSV what should I do? Is there an error page that I can redirect to? Or should I throw an exception and have the usual stack trace page show?

2021-11-18 02:26 UTC, bbielsa commented
@SamantazFox Ok so minor problem, I am trying to return a 400 error when the user uploads an invalid file, but due to the way that the existing code processes the users uploads, its not actually possible to error out and return a 400 error at this point in the code, I believe.

Here is the relevant line of code (I have not committed it yet) https://gist.github.com/bbielsa/7d131aa2188945f591a8379ec0defc9b#file-invidious-cr-L19

In this case `next` goes to the next loop of the FormData loop `HTTP::FormData.parse(env.request) do |part|`, and then at the last line of the POST handler function it redirects to the referrer `env.redirect referer`, essentially overwriting the error I am trying to show the user. 

So I was able to add the changes you asked for and I explicitly check the file extension, but if the file uploaded is of an unrecognized type, it will not show the user and error and simply redirect to the last page, not the best user experience. 

Any ideas on what I can do to work around this? Some of the ideas I had resulted in some ugly code, so I'd appreciate any contributors input or opinions.

2021-11-20 21:03 UTC, SamantazFox commented
> @SamantazFox Ok so minor problem, I am trying to return a 400 error when the user uploads an invalid file, but due to the way that the existing code processes the users uploads, its not actually possible to error out and return a 400 error at this point in the code, I believe.
> 
> Here is the relevant line of code (I have not committed it yet) https://gist.github.com/bbielsa/7d131aa2188945f591a8379ec0defc9b#file-invidious-cr-L19
> 
> In this case `next` goes to the next loop of the FormData loop `HTTP::FormData.parse(env.request) do |part|`, and then at the last line of the POST handler function it redirects to the referrer `env.redirect referer`, essentially overwriting the error I am trying to show the user.
> 
> So I was able to add the changes you asked for and I explicitly check the file extension, but if the file uploaded is of an unrecognized type, it will not show the user and error and simply redirect to the last page, not the best user experience.
> 
> Any ideas on what I can do to work around this? Some of the ideas I had resulted in some ugly code, so I'd appreciate any contributors input or opinions.

Hello ! Sorry for the late reply!

Kemal has a macro for returning a response early, even in blocks:
```
halt(env, status_code: 415,
  response: error_template(415, "Invalid subscription file uploaded")
)
```

Note that we're still using the `error_template` function to set the response's content (otherwise, there wouldn't be any HTML, just the error message specified).

(FYI: Code "415" is ["Unsupported Media Type (RFC 7231)"](https://en.wikipedia.org/wiki/HTTP_400#4xx_client_errors), which is more appropriate in this case ^^)

Also, can you please put any error message you add to the translations, with a key similar to this:
`error_message_invalid_subscription_file`? Thanks :)

2021-11-20 21:46 UTC, SamantazFox commented
@bbielsa also note that currently (i.e with the latest commit in this PR and the code you provided as a gist) the CSV import doesn't work, the request times out. There is probably an issue with the way you use the CSV module...

2021-11-30 12:14 UTC, unixfox commented
Removing from testing on https://yewtu.be

2021-12-06 02:52 UTC, SamantazFox commented
@bbielsa bump! Do you plan to finish this PR soon?

2022-01-13 11:50 UTC, SamantazFox commented
Deployed on https://test.invidious.io

2022-01-13 11:50 UTC, SamantazFox commented
@matthewmcgarvey could you please review this ?

2022-01-13 14:53 UTC, matthewmcgarvey approved these changes
Looks good 👍

2022-01-13 14:53 UTC, matthewmcgarvey commented on spec/invidious/user/imports_spec.cr
> +    expect(subscriptions).to contain("UC0hHW5Y08ggq-9kbrGgWj0A")
Just a note. `contain_exactly` is my preferred way of doing these kinds of asserts. It gives the benefit of saying it must have all these items without the drawback of having the match the order when trying to do `expect(subscriptions).to eq([...])`

https://gitlab.com/arctic-fox/spectator/-/wikis/Collection-Matchers#contain_exactly

2022-01-15 16:12 UTC, matthewmcgarvey approved these changes

2022-01-16 14:11 UTC, merged