Update to fetch related channels again
iv-org/invidious pull request #2787
Opened 2022-01-08 18:28 UTC by matthewmcgarvey

Fixes #2749

Fetching channel info seems to no longer return related channels. Instead, we have to fetch the data found in the **Channels** tab. Because this is an extra API request, I updated the code to only make it when related channels are actually used which is just one place.

The structs used in this included `DB::Serializable` but weren't actually saved to the database. I updated them to be `record`'s.

To test, go to `http://0.0.0.0:3000/api/v1/channels/UCXuqSBlHAE6Xw-yeJA0Tunw?fields=relatedChannels` on master and see that it returns an empty list. Now go to it on this branch and it should return all of the channels found in this picture
<img width="677" alt="Screen Shot 2022-01-08 at 12 27 38 PM" src="https://user-images.githubusercontent.com/17329408/148655452-3a09edd4-ae5c-4359-8cae-b55cf20ce0ba.png">

2022-01-08 18:36 UTC, matthewmcgarvey commented
This will definitely conflict with https://github.com/iv-org/invidious/pull/2215 but it's expected with mega PRs

2022-01-10 19:58 UTC, SamantazFox requested changes

2022-01-10 19:58 UTC, SamantazFox commented on src/invidious/channels/about.cr
> +        related_channels = RelatedChannels.new(browse_id: browse_id, params: params)
In regard of my other comment, this code block is not required :)

2022-01-11 00:47 UTC, SamantazFox approved these changes

2022-01-11 00:50 UTC, merged