Move last remaining routes in main file to new pattern
iv-org/invidious pull request #2925
Opened 2022-02-23 05:22 UTC by matthewmcgarvey

Related #2672
Related #2498

With this change, all routes will have been moved to the new setup.

2022-02-23 05:23 UTC, matthewmcgarvey commented on src/invidious.cr
> +CONNECTION_CHANNEL = Channel({Bool, Channel(PQ::Notification)}).new(32)
Made a constant so that it could be referenced in the route file

2022-02-23 05:23 UTC, matthewmcgarvey commented on src/invidious.cr
> +Invidious::Routing.post "/api/v1/auth/notifications", Invidious::Routes::API::V1::Authenticated, :notifications_post
Terrible names on these but not what it could be instead

2022-02-23 13:50 UTC, SamantazFox requested changes

2022-02-23 13:50 UTC, SamantazFox commented on src/invidious/routes/api/v1/authenticated.cr
> +  end
I think that you could merge those two in a single function, as the only difference is where the parameters are fetched from (`env.params.query` vs `env.params.body`).

2022-02-23 13:50 UTC, SamantazFox commented on src/invidious/routes/captcha.cr
> +module Invidious::Routes::Captcha
could you please put that under the `Login` route, as it is related to Google log-in?

2022-02-23 13:50 UTC, SamantazFox commented on src/invidious/routes/live.cr
> +module Invidious::Routes::Live
Same here: this route is related to channels, so it should go under `Invidious::Routes::Channels`

2022-02-24 15:54 UTC, SamantazFox approved these changes

2022-02-24 21:49 UTC, merged