Add watch indicators
iv-org/invidious pull request #3383
Opened 2022-11-08 22:23 UTC by WesVleuten

Added watch indicators as requested in #1195

![image](https://user-images.githubusercontent.com/16665772/200688153-c8688439-3dd1-499c-8b67-d7e245c36109.png)

With partial watch indicator if position is saved as shown in the image.

Curious to hear what you think!

2022-11-09 21:24 UTC, SamantazFox commented
Oooh, very cool, indeed!
I've some things to say on code clarity, I'll try to write a review asap ^^

2022-11-11 14:13 UTC, AHOHNMYC commented on assets/js/watched_widget.js
> +}
```suggestion
document.querySelectorAll('.watched-indicator').forEach(function (indicator) {
    var watched_part = get_all_video_times()[indicator.dataset.id];
    var total = parseInt(indicator.dataset.length, 10);
    if (watched_part === undefined) {
        watched_part = total;
    }
    var percentage = Math.round((watched_part / total) * 100);

    if (percentage < 5) {
        percentage = 5;
    }
    if (percentage > 90) {
        percentage = 100;
    }

    indicator.style.width = percentage + '%';
});
```
I'd suggest using `forEach` construction, like everywhere in Invidious, and `.dataset` to accessing `data-something` values.
With `forEach` you can omit unneeded temporary variables.
Code is not tested, but have to work :)

2023-01-07 13:42 UTC, SamantazFox requested changes

2023-01-07 13:42 UTC, SamantazFox commented on src/invidious/views/components/item.ecr
> +<% item_watched = !item.is_a?(SearchChannel) && !item.is_a?(SearchPlaylist) && !item.is_a?(InvidiousPlaylist) && !item.is_a?(Category) && env.get("user") && env.get("user").as(User).watched && env.ge
Similarly, you can chain the `env.get` part using the `.try?` method, like so:
```crystal
env.get?("user").try &.as(User).watched.index(item.id) != nil
```

`.get?` will return `nil` if "user" is not set in the HTTP context (`env`) storage. Then, if `nil` was returned, we stop here and return `nil`, orthewise we cast that returned value to a `User`-typed object and continue with the data we need.

2023-01-09 10:39 UTC, WesVleuten commented
Thanks for the review, I'll look at the requested changes asap!

2023-01-20 21:41 UTC, SamantazFox commented
Any updates on this?

2023-01-21 22:31 UTC, WesVleuten commented
Requested changed have been made, and merge conflicts have been resolved

2023-02-05 18:59 UTC, SamantazFox commented
Sorry for the lack of updates. I deployed this PR on the test instance (https://test.invidious.io).

I'm getting this error on various page, and the indicators doesn't show up:
![image](https://user-images.githubusercontent.com/52980486/216838814-c2dde31f-f187-48e8-8ca8-86275a2319fe.png)

The `watched_data` element mentioned is only present in the `history` and `subscriptions` feeds.
You should probably move your code to a separate JS file to avoid problems.

2023-02-19 15:44 UTC, SamantazFox commented
Okay, so the indicators show up (Idk why my code on the test instance had issue compiling) but their width is always 100% (likely due to the error I mentioned above)

2023-02-19 19:49 UTC, WesVleuten commented
It should be fixed now, I moved the indicator code to a different file and included it where needed

2023-02-19 22:05 UTC, SamantazFox approved these changes

2023-02-19 22:08 UTC, merged

2023-02-19 22:08 UTC, SamantazFox commented
Thanks for contributing to invidious ^^

2023-02-19 22:09 UTC, WesVleuten commented
Ofc! Happy to help!