Video: Add support for the music description section
iv-org/invidious pull request #3559
Opened 2023-01-14 12:24 UTC by techmetx11

2023-01-15 14:59 UTC, SamantazFox commented
Hello! Thanks for your PR :)

Could you also add support for videos with many songs in them? (e.g: `t3SCffJ0eEg`)

2023-01-15 16:45 UTC, techmetx11 commented
Sure thing! :)

2023-01-21 17:27 UTC, SamantazFox requested changes

2023-01-21 17:27 UTC, SamantazFox commented on src/invidious/videos/parser.cr
> +  music_desclist.try &.each do |music_desc|
```suggestion
  music_desclist = player_response.dig?(
    "engagementPanels", 1, "engagementPanelSectionListRenderer",
    "content", "structuredDescriptionContentRenderer", "items", 2,
    "videoDescriptionMusicSectionRenderer", "carouselLockups"
  )
  
  music_desclist.try &.as_a.each do |music_desc|

2023-01-21 17:27 UTC, SamantazFox commented on src/invidious/videos/parser.cr
> +  music_desclist.try &.each do |music_desc|
Proposition adds wrapping for clarity, and uses a single `.try`

2023-01-21 17:28 UTC, SamantazFox commented
Regarding the HTML, what do you think about using the section title as the toggle, instead of the "show more/less" button?

![image](https://user-images.githubusercontent.com/52980486/213875248-ff459648-c7ab-4e43-aa88-e3ec6a34f3fb.png)
![image](https://user-images.githubusercontent.com/52980486/213875307-cfad348b-7120-418d-ad98-13e5b38031ce.png)

For your information, I used the following for the arrows:
`<i class="icon ion-ios-arrow-up"></i>`
`<i class="icon ion-ios-arrow-down"></i>`

2023-01-21 17:49 UTC, techmetx11 commented
> Regarding the HTML, what do you think about using the section title as the toggle, instead of the "show more/less" button?
> 
> ![image](https://user-images.githubusercontent.com/52980486/213875248-ff459648-c7ab-4e43-aa88-e3ec6a34f3fb.png) ![image](https://user-images.githubusercontent.com/52980486/213875307-cfad348b-7120-418d-ad98-13e5b38031ce.png)
> 
> For your information, I used the following for the arrows: `<i class="icon ion-ios-arrow-up"></i>` `<i class="icon ion-ios-arrow-down"></i>`
Seems alot more better, Also thanks for your reviews :)

2023-02-02 20:48 UTC, SamantazFox approved these changes

2023-02-02 21:15 UTC, merged

2023-02-02 21:36 UTC, SamantazFox commented
Thanks for contributing to invidious :D