Bump videoJS dependencies
iv-org/invidious pull request #3584
Opened 2023-01-20 23:21 UTC by SamantazFox

Patch courtesy of therealresonix (Matrix)

Bump `videojs` to v7.21.1
Bump `videojs-contrib-quality-levels` to v3.0.0
Bump `videojs-mobile-ui` to v1.0.1
Bump `videojs-overlay` to v3.0.0
Bump `videojs-vr` to v1.10.1

---

Note: This will likely require forking and updating [videojs-http-source-selector](https://github.com/jfujita/videojs-http-source-selector) (See https://github.com/iv-org/invidious/pull/3011#issue-1197546033)

2023-01-21 08:21 UTC, unixfox commented
> Note: This will likely require forking and updating [videojs-http-source-selector](https://github.com/jfujita/videojs-http-source-selector) (See https://github.com/iv-org/invidious/pull/3011#issue-1197546033)

Freetube is maintaining a fork: https://github.com/FreeTubeApp/videojs-http-source-selector

2023-01-21 08:24 UTC, unixfox requested changes
Can't be merged without fixing the issues with videojs-http-source-selector

2023-02-02 22:37 UTC, absidue commented
@ChunkyProgrammer has been working on a fork on the FreeTube org: https://github.com/FreeTubeApp/videojs-http-source-selector

2024-03-02 05:15 UTC, ChunkyProgrammer commented
Related: https://github.com/iv-org/invidious/pull/4439/

2024-08-17 17:46 UTC, closed without merging

2024-08-17 17:48 UTC, SamantazFox commented
We'll jump straight to VJS8 -> #4439