Playlists: Use subtitle when author is missing
iv-org/invidious pull request #4025
Opened 2023-08-01 16:02 UTC by ChunkyProgrammer

Example playlists:
One artist: https://www.youtube.com/playlist?list=OLAK5uy_lM3m05hKVY9vbzZH5lJpVKZKUQ-v_iTz4
Two artists: https://www.youtube.com/playlist?list=OLAK5uy_mYnfMbIG74obySLdWtKKGj_MJ-YZqVTu0

Related:
https://github.com/LuanRT/YouTube.js/pull/458

Screenshots:

<details>
<summary>Without this PR (Artist not displayed)</summary>
<img alt="Empty artist field" src="https://github.com/iv-org/invidious/assets/78101139/060553bd-028e-4591-a4c9-66358631c229">
</details>

<details>
<summary>With this PR (one artist displayed):</summary>
<img alt="SIA as the artist" src="https://github.com/iv-org/invidious/assets/78101139/d53fb754-815d-41b8-9fab-4138d5c2eac7">
</details>

<details>
<summary>With this PR (two artists displayed)</summary>
<img alt="SIA and David Guetta as the artist" src="https://github.com/iv-org/invidious/assets/78101139/0e483bcf-36b1-451f-95d0-2c31c8b2cf77">
</details>

2023-08-06 17:39 UTC, syeopite requested changes

2023-08-06 17:39 UTC, syeopite commented on src/invidious/views/playlist.ecr
> +                    <span><%= playlist.subtitle.try &.split(" • ")[0] %></span> |
Please sanitize `playlist.subtitle`

2023-08-07 19:13 UTC, syeopite approved these changes

2023-08-28 19:29 UTC, SamantazFox approved these changes

2023-09-18 21:34 UTC, merged

2023-09-18 21:35 UTC, SamantazFox commented
Thanks for the PR :D