Update crystal version matrix in ci.yml
iv-org/invidious pull request #4095
Opened 2023-09-10 19:52 UTC by SamantazFox

Drop 1.4 and 1.5 branches
Add 1.9 branch

2023-09-10 20:01 UTC, syeopite requested changes
Can you also bump `install-crystal` to 1.8.0?

2023-09-10 20:15 UTC, SamantazFox commented
Done!

2023-09-10 21:37 UTC, syeopite approved these changes

2023-09-16 09:56 UTC, SamantazFox commented
Rebased my changes because of https://github.com/iv-org/invidious/commit/cc03610325f8c49b14216f2913a8a3148b48e3a2

2023-09-16 10:22 UTC, unixfox approved these changes

2023-09-18 21:34 UTC, merged