Add sort options to streams
iv-org/invidious pull request #4224
Opened 2023-11-01 18:33 UTC by src-tinkerer

Uses the same method that is used for videos. We create continuation based on the sort option. One note though, `produce_channel_livestreams_continuation` and `produce_channel_videos_continuation` are almost identical, so isn't it better to simply make a singular function that produces the continuation based on the content?

2023-11-13 21:24 UTC, SamantazFox commented
Yes, merging the two in a single function is strongly preferred.
Also, please remove `produce_channel_livestream_url`. It has no use (the function you copied, `produce_channel_videos_url` was only used to bypass captchas back then and will be discarded one day).

2023-11-22 11:30 UTC, src-tinkerer commented
I made the requested changes but couldn't test it yet because YouTube is blocked in my country, shouldn't be merged until then.

2023-11-23 22:00 UTC, SamantazFox requested changes
Code looks good! I'm only asking for a few style/syntax changes ^^

2023-11-24 21:25 UTC, src-tinkerer commented on src/invidious/channels/videos.cr
> +def produce_channel_content_continuation(ucid, content, page = 1, auto_generated = nil, sort_by = "newest", v2 = false)
Done

2023-11-24 21:27 UTC, src-tinkerer commented on src/invidious/routes/channels.cr
> +    sort_by = env.params.query["sort_by"]?.try &.downcase
> For consistency with what you did in `routes/api/v1/channels.cr` (don't forget to also change the line underneath, as I can't make a suggection across two separate diff chunks)

The thing is this is how it's done with videos in `src/invidious/routes/channels.cr`. Also what line underneath? `sort_options = {"newest", "oldest", "popular"}` ?

2023-11-24 21:27 UTC, src-tinkerer commented on src/invidious/channels/videos.cr
> +def produce_channel_content_continuation(ucid, content, page = 1, auto_generated = nil, sort_by = "newest", v2 = false)
Done

2023-11-24 21:27 UTC, src-tinkerer commented on src/invidious/channels/videos.cr
> +      continuation ||= make_initial_content_ctoken(channel.ucid, "livestreams", sort_by)
Done

2023-11-25 17:10 UTC, SamantazFox commented on src/invidious/routes/channels.cr
> +    sort_by = env.params.query["sort_by"]?.try &.downcase
In the line where you're doing `(sort_by || "newest")` !

2023-11-28 22:43 UTC, SamantazFox commented on src/invidious/routes/channels.cr
> +      channel, continuation: continuation, sort_by: (sort_by || "newest")
To go with my other code suggestion:
```suggestion
      channel, continuation: continuation, sort_by: sort_by
```

2023-11-30 11:05 UTC, src-tinkerer commented
Done, sorry for delay. Been busy with midterms.

2023-11-30 20:34 UTC, SamantazFox approved these changes

2024-03-17 12:27 UTC, src-tinkerer commented
Will test this week

2024-03-26 12:24 UTC, src-tinkerer commented
Okay done testing and live stream sort works.

2024-04-27 20:48 UTC, SamantazFox approved these changes

2024-05-10 17:57 UTC, src-tinkerer commented
Is this getting merged? xD

2024-07-10 20:30 UTC, merged

2024-07-10 20:30 UTC, SamantazFox commented
Thanks for your contribution :)