Batch user notifications together
iv-org/invidious pull request #4486
Opened 2024-03-15 22:58 UTC by 999eagle

This PR changes how user notifications are handled. Both the `RefreshChannelsJob` and incoming pubsub webhooks are changed here to not directly persist notifications or the feed update flag to the database. A new job (or rather, a new fiber in the `NotificationJob` as I thought that'd be a good place to put this) handles all notifications and periodically writes them to the database batched by channels. With this change the `RefreshChannelsJob` now also correctly (at least that's my understanding) notifies the `/api/v1/auth/notifications` endpoint through the PostgreSQL `NOTIFY/LISTEN` mechanism already in use.
This greatly reduces the write load on the database when a channel has multiple video updates within the job timeout (i.e. 1 minute currently). From my testing this does seem to happen pretty often, especially when the `RefreshChannelsJob` runs at instance restart after the previous instance's backoff time for the job got too high.

2024-04-15 06:00 UTC, unixfox commented
Could you take a look at @syeopite and @SamantazFox :)?

2024-07-14 12:59 UTC, 999eagle commented
not stale, still using this pr on iv.catgirl.cloud and waiting for a review

2024-08-24 23:01 UTC, SamantazFox requested changes

2024-08-26 19:44 UTC, 999eagle commented
thanks for the suggestions, applied those! not sure if the mutex is done correctly now, no idea how mutexes should be used in crystal really..

2024-08-26 22:30 UTC, SamantazFox commented
> thanks for the suggestions, applied those! not sure if the mutex is done correctly now, no idea how mutexes should be used in crystal really..

My knowledge on the subject is quite new, but I think that [`.synchronize`](https://github.com/crystal-lang/crystal/blob/04998c0c7/src/mutex.cr#L140) is better as it handles errors nicely and ensures that the Mutex is always unlocked. It is also much clearer where the unsafe section of code starts and ends:
```crystal
some_mutex.synchronize do
  # Stuff
end
```

2024-08-27 08:50 UTC, 999eagle commented
ah, thanks! changed the mutex to use `.synchronize`

2024-10-31 13:07 UTC, SamantazFox approved these changes

2025-02-26 22:28 UTC, merged