Add field for `authorVerified` for recommended videos when using the API
iv-org/invidious pull request #4562
Opened 2024-04-05 00:22 UTC by ChunkyProgrammer

https://github.com/iv-org/invidious/issues/3323

2024-04-07 19:42 UTC, syeopite requested changes
This is currently returning as a string instead of a bool.

You'll have to modify the `video.related_videos` property as well as each attribute under it is converted into a string.

https://github.com/iv-org/invidious/blob/08390acd0c17875fddb84cabba54197a5b5740e4/src/invidious/videos.cr#L91-L93

2024-04-16 22:23 UTC, ChunkyProgrammer commented
> `rv["author_verified"]` is currently returning as a string instead of a bool.
> 
> You'll have to modify the `video.related_videos` property as well as each attribute under it is currently converted into a string.
> 
> https://github.com/iv-org/invidious/blob/08390acd0c17875fddb84cabba54197a5b5740e4/src/invidious/videos.cr#L91-L93

Other parts of the code assumes that author_verified is a string so I just switched to checking if it's equal to "true" for the api instead of refactoring

2024-04-20 14:51 UTC, SamantazFox commented
> Other parts of the code assumes that author_verified is a string so I just switched to checking if it's equal to "true" for the api instead of refactoring

Yes, you can do `if rv["author_verified"]? == "true"` like it's done on the HTML side.

2024-04-20 14:51 UTC, SamantazFox approved these changes

2024-04-20 14:52 UTC, SamantazFox commented
@syeopite One day this will be refactored, but today is not that day x)

2024-04-26 22:36 UTC, merged