Add release based containers
iv-org/invidious pull request #4763
Opened 2024-06-24 18:51 UTC by syeopite

- Changes the current master based container to use "master" tag instead of "latest" tag
- Adds a new workflow to build a container on each new release which has  the "latest" tag, and a tag based on the current released version.

2024-06-25 00:34 UTC, iBicha commented
> Changes the current master based container to use "master" tag instead of "latest" tag

`stable` might be more commonly used/understood. Or even `production`.
Very good initiative!

2024-06-25 03:16 UTC, syeopite commented
The release containers are tagged as "latest" as to ensure a smooth transition for instances. 

As testing is being moved to per-release with this PR, instances should be using the release containers instead of the container built off master as to ensure instance stability.

2024-06-25 21:13 UTC, iBicha commented
> The release containers are tagged as "latest" as to ensure a smooth transition for instances.
> 
> As testing is being moved to per-release with this PR, instances should be using the release containers instead of the container built off master as to ensure instance stability.

Fair enough, I take my comment back

2024-07-01 20:07 UTC, SamantazFox commented
Could you rename the two files to something in the odds of `container-release` and `container-nightly` (or whatever you see fit)? The two names are too similar, that's confusing!

2024-07-03 22:09 UTC, SamantazFox requested changes

2024-07-03 22:09 UTC, SamantazFox commented on .github/workflows/build-stable-container.yml
> +            type=semvar,pattern={{version}}
Small typo
```suggestion
            type=semver,pattern={{version}}
```
Reference: https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver

2024-07-03 22:09 UTC, SamantazFox commented on .github/workflows/build-stable-container.yml
> +          crystal: 1.12.2
Commenting here, but can you bump the other file to the same version?

2024-07-03 22:09 UTC, SamantazFox commented on .github/workflows/build-stable-container.yml
> +            type=semvar,pattern={{version}}
```suggestion
            type=semver,pattern={{version}}
```

2024-07-09 22:22 UTC, SamantazFox commented
Marking as ready as the only option to trigger that is to merge the code and publish a new tagged release.

2024-07-09 22:53 UTC, unixfox approved these changes

2024-07-10 20:30 UTC, merged