Add the ability to listen on UNIX sockets
iv-org/invidious pull request #5112
Opened 2024-12-14 00:58 UTC by Caian

This is a continuation of #2111 that was closed. 

As stated in the original PR, using unix sockets can have a beneficial impact on performance. I found that particularly relevant when running my invidious instance in a rootless container.

This PR adds the `socket_binding` option to config that specifies a socket to listen to. The `socket_binding` option will disable listening to TCP. I also added `socket_permissions` because often one needs to control who accesses the socket.

2024-12-14 01:01 UTC, Caian commented
Tested and running on my personal invidious behind a Caddy proxy with https enabled. Now videojs buffers the video much faster and the user-mode networking on the server consumes a less CPU and RAM.

2024-12-14 06:27 UTC, unixfox requested changes
Maybe you can combine the two parameters into one.

And make sure to comment them otherwise socket binding will be on by default!

2024-12-14 08:42 UTC, Caian commented
> Maybe you can combine the two parameters into one.
> 
> And make sure to comment them otherwise socket binding will be on by default!

Ops, I fixed the configuration file to leave it disable. I prefer the idea of leaving separate parameters for clarity, but if the parameters were to be combined I was thinking of doing something like:

socket_binding: /tmp/invidious.socket,777

What do you think?

2024-12-14 16:17 UTC, unixfox commented
> > Maybe you can combine the two parameters into one.
> > 
> > And make sure to comment them otherwise socket binding will be on by default!
> 
> Ops, I fixed the configuration file to leave it disable. I prefer the idea of leaving separate parameters for clarity, but if the parameters were to be combined I was thinking of doing something like:
> 
> socket_binding: /tmp/invidious.socket,777
> 
> What do you think?

You can also do it this way:

socket_binding:
  path: /tmp/invidious.socket
  permission: 777

2024-12-14 18:18 UTC, Caian commented
> > > Maybe you can combine the two parameters into one.
> > > And make sure to comment them otherwise socket binding will be on by default!
> > 
> > 
> > Ops, I fixed the configuration file to leave it disable. I prefer the idea of leaving separate parameters for clarity, but if the parameters were to be combined I was thinking of doing something like:
> > socket_binding: /tmp/invidious.socket,777
> > What do you think?
> 
> You can also do it this way:
> 
> socket_binding: path: /tmp/invidious.socket permission: 777

I like this solution, implemented.

2024-12-16 14:21 UTC, unixfox requested changes

2024-12-17 23:32 UTC, Caian commented on config/config.example.yml
> -##
Sorry I'll revert that, my editor automatically removed a trailing space...

2024-12-17 23:32 UTC, Caian commented on src/invidious/config.cr
> +  property socket_binding : SocketBindingConfig? = nil
Sure, I'll take a look!

2025-01-05 01:19 UTC, syeopite requested changes

2025-01-05 01:19 UTC, syeopite commented on src/invidious.cr
> +    socket_binding = CONFIG.socket_binding.not_nil!
```suggestion
  if socket_binding = CONFIG.socket_binding
```

2025-01-05 01:19 UTC, syeopite commented on src/invidious.cr
> +    end
This can be simplified to `File.delete?`

https://crystal-lang.org/api/1.14.0/File.html#delete%3F(path%3APath|String)%3ABool-class-method

```suggestion
File.delete?(socket_binding.path)
```

2025-01-05 01:19 UTC, syeopite commented on src/invidious/config.cr
> +      sb = config.socket_binding.not_nil!
```suggestion
    if sb = config.socket_binding
```

2025-01-05 21:51 UTC, syeopite approved these changes

2025-02-26 22:28 UTC, merged