WIP/Feedback: Homepage welcome message (#740)
iv-org/invidious pull request #744
Opened 2019-09-08 15:11 UTC by girst

# rationale

New users are often confused what invidious is. Adding a welcome message (similar to e.g. GitHub's or old.Reddit's) gives us the opportunity to introduce ourselves and provide the user with a 'call to action' (signing up). 
The wording is kept mostly jargon-free (e.g. "youtube-player" instead of "-frontend") to be friendly to non-technical folks. 

Another change is more subtle: some users think, invidious is an alternative video hosting site. Switching the home page to 'popular' by default shows the user a bunch of familiar channels/faces they might recognize, emphasizing that content comes from Youtube.

The data import page has been updated as well, with a simple two-step guide for the most common action, importing subscriptions from Youtube.

# requested feedback

We need to decide on which roughly 5 features we want to advertise on the homepage and the final wording of the welcome message and call to action.

Text right now:
> **Welcome to Invidious**
> Invidious is a community developed Youtube-player, that respects your privacy. Features include:
>  * Ad-free
>  * Audio-only mode
>  * Works without Javascript
>  * No Google account required
>  * Download video, audio and subtitles
>  * and many more *(links to README.md)*
>
>  **create an account and import your subscriptions now**  *(links to register page, redirects to data import)*

# TODO

after the text has been finalized, it needs to be localized. 

----

fixes #740

2019-09-11 21:52 UTC, girst commented
I'm stuck; maybe a crystal-expert can help me out here: I've generalized the dismissal system, so more than one infobox could be dismissed in the future. For this, I wanted to store which ones have been dismissed in either an Array(String) or a Hash(String, Bool) and push an element for each infobox. But then the preference appears to be shared between users!? If I dismiss it in one session, it's gone for all others too!

2019-10-11 18:50 UTC, omarroth commented
Thanks for this! Apologies for not jumping on it sooner.

As mentioned in [#227](https://github.com/omarroth/invidious/issues/227#issuecomment-466800711) and #457, I would very much like to have this as an `/about` page, so it doesn't take up as much space on the homepage. Having a dismissal system works, however I think having a separate page is quite a bit simpler and provides more room for any additional information (FAQ, etc). 

Language is good. Feature selection looks good.

I agree "Popular" makes sense as the default home page. I expect the default to be changed as part of #295 so that it's still possible for current users to switch back if they prefer.

2019-10-11 19:52 UTC, girst commented
On Fri, Oct 11, 2019 at 11:50:35AM -0700, Omar Roth wrote:
>Thanks for this! Apologies for not jumping on it sooner.

no worries, we're all just doing this in our spare time!

> I would very much like to have this as an `/about` page, so 
>it doesn't take up as much space on the homepage. Having a dismissal 

an about page would be nice to have too, but I think, showing a message 
on first arrival is important. I can tune it to take up less vertical 
space though (I'll put together a rough mock-up).

reason being that most people won't click a link to the about page, but 
just leave the homepage confused.

>system works, however I think having a separate page is quite a bit 
>simpler and provides more room for any additional information (FAQ, 
>etc).

the "and many more" link could link to that /about page (possibly with a 
different label). again: i think it is very important that we give 
_some_ message on the homepage, even if we trim it down considerably.

>
>Language is good. Feature selection looks good.
>
>I agree "Popular" makes sense as the default home page. I expect the 
>default to be changed as part of #295 so that it's still possible for 
>current users to switch back if they prefer.

the way I've implemented the current version of the patch allows this 
already, no? I can submit that as its own PR if you prefer.

>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/omarroth/invidious/pull/744#issuecomment-541182065

2019-10-11 20:35 UTC, girst commented
![mockup](https://imgur.com/AYVD6MW.png)
<details>
```
<div style="border-bottom: 1px solid #ddd;">
  <a style="float:right" href="/dismiss_info?name=welcome">dismiss</a><h1 style="font-size:1.4em">Welcome to Invidious</h1>

<p>Invidious is a community developed Youtube-player that respects your privacy. Features include
  </p><ul>
    <li>Ad-Free
      </li><li>Audio-only mode
        </li><li>Subscriptions without a Google account
            </li><li>Download videos, audio and subtitles
  </li><li><a href="/about">Click to learn more</a>
    </li></ul>


</div>

```
</details>

![mockup](https://imgur.com/XPHfg4q.png)
<details>
```

<div style="border-bottom: 1px solid #ddd;border-top: 1px solid #ddd;">
  <a style="float:right;margin: .67em;" href="/dismiss_info?name=welcome">dismiss</a><h1 style="font-size:1.4em">Welcome to Invidious</h1>

<p>Invidious is a community developed Youtube-player that respects your privacy. It is <b>Ad-Free</b>, has an <b>Audio-only mode</b>, lets you have <b>Subscriptions without a Google account</b>, <b>Download videos, audio and subtitles</b> and much, much more!
  </p><p><a href="/about">Click to learn more</a>
</p></div>


```
</details>

2019-10-22 18:06 UTC, girst commented
i have made the welcome message much smaller and reworded it (only 3 features instead of 5). screenshot and text in pullreq-description.

2020-07-22 20:26 UTC, comradekingu commented on src/invidious/views/components/welcome_message.ecr
> +        <p>Watch Youtube-videos <em>Ad-free</em>, <em>download videos, audio and subitles</em>, <em>subscribe to channels</em> without Google tracking you and <a href="https://github.com/omarroth/inv
```suggestion
        <p>Watch YouTube-videos <em>ad-free</em>, <em>download videos, audio and subtitles</em>, <em>subscribe to channels</em> without Google tracking you and <a href="https://github.com/omarroth/invidious/blob/master/README.md" id="learn_more_link">much, much more</a>.
```

2020-07-22 20:29 UTC, comradekingu commented on locales/en-US.json
> +    "click here to download your YouTube-Takeout": "click here to download your YouTube-Takeout",
```suggestion
    "click here to download your YouTube-Takeout": "click here to download your YouTube Takeout",
```
As per https://en.wikipedia.org/wiki/Google_Takeout

2020-07-22 20:30 UTC, comradekingu commented on src/invidious/views/data_control.ecr
> +            <%= translate(locale, "click here to download your YouTube-Takeout") %>
```suggestion
            <%= translate(locale, "click here to download your YouTube Takeout") %>
```

2020-07-22 22:48 UTC, girst commented
Those changes LGTM, thanks! Are you interested in working on it? I don't have the time (and since built my own invidious-alternative, subscriptions.gir.st) to fix the (trivial) merge conflicts, so feel free to push more commits as you please.

2020-09-13 20:42 UTC, comradekingu commented
@girst
"Click here to import your subscriptions from YouTube in the form of a \"YouTube Takeout\" file you can send in below."

Oh, I understood what I was meant to do now ;)

> Welcome
> This is one of many Invidious instances; where you can watch and download video, audio and subtitles ad-free. Free [your YouTube subscriptions] from Google by [making an account here]. Avoid even the last bit of tracking by using the [Tor Browser].

2020-09-13 20:48 UTC, comradekingu requested changes
Commented in the thread :)

2020-09-14 10:36 UTC, girst commented
On Sun, Sep 13, 2020 at 01:42:29PM -0700, Allan Nordhøy wrote:
>@girst
>"Click here to import your subscriptions from YouTube in the form of a \"YouTube Takeout\" file you can send in below."
>
>Oh, I understood what I was meant to do now ;)

not sure what you want from me here. 

>> Welcome
>> This is one of many Invidious instances; where you can watch and download video, audio and subtitles ad-free. Free [your YouTube subscriptions] from Google by [making an account here]. Avoid even the last bit of tracking by using the [Tor Browser].

i guess this is a requested update to the welcome message? as i said 
earlier, please make any changes to this pr yourself (i believe you have 
commit access?); i don't have the time to work on invidious any more.

however, i would suggest against recommending the tor browser. video 
streaming is really hard on the network, and i see no indication that 
google is using googlevideo-streams to track people (it afair doesn't 
even use cookies or etags).

2021-06-19 14:26 UTC, SamantazFox commented
bump, still relevant (though it probably will require to be redone from zero, as code changed a lot).

2021-06-22 11:33 UTC, syeopite commented
Sure, it may still be relevant but the PR is essentially abandoned; no one has forked and continued working on it either. It may be better to just close the PR*. Either way, seeing as this is still an issue I'm just going to go ahead and open #740 again.

*This is mostly just my take on the stale PR handler and why I shortened the length. PRs should be *active* imo and anything that hasn't received any activity for more than 45 days can likely be considered abandoned.

2021-06-22 14:50 UTC, SamantazFox commented
yeah, but the idea's good, and there was already some work / review done, so that would be sad to dump it. The welcome message is simple and looks good, though there are some improvements to make (for translations, especially).

2021-09-30 01:11 UTC, closed without merging